<a href="https://colab.research.google.com/github/chanukaDissanayaka/RideFareClassification/blob/master/Ridefare_submission_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#imports

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix

from datetime import datetime, timedelta
from pandas import DataFrame

from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier

import numpy as np

RANDOM_SEED = 4

Using TensorFlow backend.


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [ ]:
#dataframe = pd.read_csv("/content/train.csv")
#test = pd.read_csv("/content/test.csv")

dataframe = pd.read_csv("/content/gdrive/My Drive/ML_RideFare/Data/train.csv")
test = pd.read_csv("/content/gdrive/My Drive/ML_RideFare/Data/test.csv")

dataframe.isna().sum(axis = 0)
#dataframe = dataframe.fillna(method='ffill')
#dataframe = dataframe.dropna()

tripid                         0
additional_fare              202
duration                     202
meter_waiting                202
meter_waiting_fare           202
meter_waiting_till_pickup    202
pickup_time                    0
drop_time                      0
pick_lat                       0
pick_lon                       0
drop_lat                       0
drop_lon                       0
fare                         137
label                          0
dtype: int64

In [ ]:
def preprocess_train_data(dataframe):
  feature_set = dataframe.iloc[:,1:13]

  features = feature_set

  features['pickup_time'] = pd.to_datetime(features['pickup_time'], format="%m/%d/%Y %H:%M")
  features['drop_time'] = pd.to_datetime(features['drop_time'], format="%m/%d/%Y %H:%M")

  td = features

  td['pickup_time_year'] = td['pickup_time'].dt.year
  td['pickup_time_month'] = td['pickup_time'].dt.month
  td['pickup_time_day'] = td['pickup_time'].dt.day
  td['pickup_time_hour'] = td['pickup_time'].dt.hour
  td['pickup_time_minute'] = td['pickup_time'].dt.minute

  td['drop_time_year'] = td['drop_time'].dt.year
  td['drop_time_month'] = td['drop_time'].dt.month
  td['drop_time_day'] = td['drop_time'].dt.day
  td['drop_time_hour'] = td['drop_time'].dt.hour
  td['drop_time_minute'] = td['drop_time'].dt.minute

  td['day_of_week'] = td['pickup_time'].dt.day_name()
  td['day_of_week'] = OrdinalEncoder().fit_transform(td[['day_of_week']])

  td['duration_calculated'] = td['drop_time'] - td['pickup_time']
  td['duration_calculated'] = td['duration_calculated'].dt.total_seconds().astype(int)

  td = td.drop('pickup_time',1)
  td = td.drop('drop_time',1)

  td = get_trip_distance_eucld(td)
  td = get_X_distance(td)
  td = get_Y_distance(td)
  td = get_pick_XY(td)
  td = get_drop_XY(td)
  td = transform_hour(td)
  td = set_fare_duration(td)
  td = calculate_direction(td)
  td = set_driving_duration(td)
  td = get_exact_fare(td)
  td = get_manhtn_distance(td)
  

  return td

def get_labels(dataframe):
  label_set = dataframe.iloc[:, 13:14]
  #rev_label_set = label_set
  rev_label_set = label_set.replace({'correct':'incorrect', 'incorrect':'correct'})

  encoder = LabelEncoder()
  encoder.fit(rev_label_set)
  labels = encoder.transform(rev_label_set)
  return labels

def set_time_of_the_day(cleaned_train_set):
  cleaned_train_set.head()
  newFrame = cleaned_train_set
  tt = newFrame

  d0_index = newFrame[(newFrame['pickup_time_hour']>=0) & (newFrame['pickup_time_hour'] < 6 )].index
  tt.loc[d0_index,'time_of_day']=0

  d1_index = newFrame[(newFrame['pickup_time_hour']>=6) & (newFrame['pickup_time_hour'] < 12 )].index
  tt.loc[d1_index,'time_of_day']=1

  d2_index = newFrame[(newFrame['pickup_time_hour']>=12) & (newFrame['pickup_time_hour'] < 18 )].index
  tt.loc[d2_index,'time_of_day']=2

  d3_index = newFrame[(newFrame['pickup_time_hour']>=18) & (newFrame['pickup_time_hour'] < 24 )].index
  tt.loc[d3_index,'time_of_day']=3

  return tt

def haversine_distance(lat1, lon1, lat2, lon2):
  r = 6371
  phi1 = np.radians(lat1)
  phi2 = np.radians(lat2)
  d_phi = np.radians(lat2-lat1)
  d_lambda = np.radians(lon2-lon1)

  a = np.sin(d_phi /2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(d_lambda/2)**2
  res = r*(2* np.arctan2(np.sqrt(a), np.sqrt(1-a)))

  return np.round(res,2)
  return res

def get_trip_distance(frame):
  newFrame = frame
  newFrame["distance"] = haversine_distance(frame['pick_lat'],frame['drop_lat'],frame['pick_lon'],frame['drop_lon'])
  return newFrame

def get_trip_distance_eucld(frame):
  newFrame = frame
  newFrame["distance"] = (((frame['pick_lat']-frame['drop_lat'])**2)+((frame['pick_lon']-frame['drop_lon'])**2)**0.5)
  return newFrame

def get_X_distance(frame):
  newFrame = frame
  newFrame["distance_X"] = ((frame['pick_lat']-frame['drop_lat']))
  return newFrame

def get_Y_distance(frame):
  newFrame = frame
  newFrame["distance_Y"] = ((frame['pick_lon']-frame['drop_lon']))
  return newFrame

def get_manhtn_distance(frame):
  newFrame = frame
  newFrame["distance_mnhtn"] = ((abs(frame['distance_X'])+abs(frame['distance_Y'])))
  return newFrame

def get_pick_XY(frame):
  newFrame = frame
  newFrame["pick_X"] = np.cos(frame['pick_lat'])* np.cos(frame['pick_lon'])
  newFrame["pick_Y"] = np.cos(frame['pick_lat'])* np.sin(frame['pick_lon'])
  return newFrame

def get_drop_XY(frame):
  newFrame = frame
  newFrame["drop_X"] = np.cos(frame['drop_lat'])* np.cos(frame['drop_lon'])
  newFrame["drop_Y"] = np.cos(frame['drop_lat'])* np.sin(frame['drop_lon'])
  return newFrame

def transform_hour(frame):
  newFrame = frame
  newFrame["pick_hour_sin"] = np.sin(np.radians(3*frame['pickup_time_hour']))
  newFrame["drop_hour_sin"] = np.sin(np.radians(3*frame['drop_time_hour']))

  newFrame["pick_hour_cos"] = np.cos(np.radians(3*frame['pickup_time_hour']))
  newFrame["drop_hour_cos"] = np.cos(np.radians(3*frame['drop_time_hour']))
  return newFrame

def set_fare_duration(imputed_train_set):
  df = imputed_train_set

  df['total_fare'] = ((df['fare']-df['fare'].mean())/df['fare'].std() +
                      (df['additional_fare']-df['additional_fare'].mean())/df['additional_fare'].std()+ 
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std())

  df['total_fare'] =  df['fare'] + df['additional_fare'] + df['meter_waiting_fare']
  df['total_additional_fare'] = df['additional_fare'] + df['meter_waiting_fare']
  df['total_waiting_time'] = df['meter_waiting'] + df['meter_waiting_till_pickup']
  df['total_time'] = df['total_waiting_time'] + df['duration']

  df['waiting_factor'] = ((df['meter_waiting']-df['meter_waiting'].mean())/df['meter_waiting'].std() +
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std()+ 
                      (df['meter_waiting_till_pickup']-df['meter_waiting_till_pickup'].mean())/df['meter_waiting_till_pickup'].std())

  return df

def calculate_direction(frame):
    newFrame = frame

    distance_X = frame['distance_X']
    distance_Y = frame['distance_Y']

    result = np.zeros(len(distance_X))
    l = np.sqrt(distance_X**2 + distance_Y**2)
    result[distance_X>0] = (180/np.pi)*np.arcsin(distance_Y[distance_X>0]/l[distance_X>0])
    idx = (distance_X<0) & (distance_Y>0)
    result[idx] = 180 - (180/np.pi)*np.arcsin(distance_Y[idx]/l[idx])
    idx = (distance_X<0) & (distance_Y<0)
    result[idx] = -180 - (180/np.pi)*np.arcsin(distance_Y[idx]/l[idx])
    newFrame['direction'] = result
    return newFrame

def set_driving_duration(train_set):
  df = train_set

  df['driving_duration'] = df['duration'] - df['meter_waiting']
  return df

def get_exact_fare(train_set):
  df = train_set
  df['exact_fare'] = df['fare'] - df['additional_fare']- df['meter_waiting_fare']
  return df

In [ ]:
print(dataframe.label.value_counts())

correct      15495
incorrect     1681
Name: label, dtype: int64


In [ ]:
cleaned_train_set = preprocess_train_data(dataframe)
labels = get_labels(dataframe)
cleaned_train_set.head()


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


additional_fare  duration  ...  exact_fare  distance_mnhtn
0             10.5     834.0  ...    259.8200         0.06178
1             10.5     791.0  ...    187.3500         0.03394
2             10.5    1087.0  ...    291.1400         0.07780
3             10.5     598.0  ...     56.1362         0.00938
4              NaN       NaN  ...         NaN         0.09713

[5 rows x 42 columns]

In [ ]:
#drop outliers

data_exp = cleaned_train_set
data_exp['labels'] = labels

#data_exp = data_exp[data_exp.duration<=10000]
data_exp = data_exp[data_exp.drop_lon>70.0]
data_exp = data_exp[data_exp.drop_lat<10.0]
#data_exp = data_exp[data_exp.meter_waiting<=20000]
#data_exp = data_exp[data_exp.meter_waiting_till_pickup<=1000]
data_exp.head()

additional_fare  duration  meter_waiting  ...  exact_fare  distance_mnhtn  labels
0             10.5     834.0           56.0  ...    259.8200         0.06178       1
1             10.5     791.0           47.0  ...    187.3500         0.03394       1
2             10.5    1087.0           80.0  ...    291.1400         0.07780       1
3             10.5     598.0          271.0  ...     56.1362         0.00938       1
4              NaN       NaN            NaN  ...         NaN         0.09713       1

[5 rows x 43 columns]

In [ ]:
from sklearn.impute import SimpleImputer

data_exp.duration.fillna(data_exp.duration_calculated, inplace=True)
data_exp.additional_fare.fillna(10.5, inplace=True)
data_exp.meter_waiting.fillna(data_exp.meter_waiting.mean(), inplace=True)
data_exp.meter_waiting_fare.fillna(data_exp.meter_waiting*0.3, inplace=True)
data_exp.head()

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
dframe = imp_mean.fit_transform(data_exp)
k = data_exp.keys()
imputed_set = data_exp
imputed_set[k] = dframe
imputed_set.head()

additional_fare  duration  meter_waiting  ...  exact_fare  distance_mnhtn  labels
0             10.5     834.0      56.000000  ...  259.820000         0.06178     1.0
1             10.5     791.0      47.000000  ...  187.350000         0.03394     1.0
2             10.5    1087.0      80.000000  ...  291.140000         0.07780     1.0
3             10.5     598.0     271.000000  ...   56.136200         0.00938     1.0
4             10.5    1020.0     629.108349  ...  266.904108         0.09713     1.0

[5 rows x 43 columns]

In [ ]:
imputed_set.head()

additional_fare  duration  meter_waiting  ...  exact_fare  distance_mnhtn  labels
0             10.5     834.0      56.000000  ...  259.820000         0.06178     1.0
1             10.5     791.0      47.000000  ...  187.350000         0.03394     1.0
2             10.5    1087.0      80.000000  ...  291.140000         0.07780     1.0
3             10.5     598.0     271.000000  ...   56.136200         0.00938     1.0
4             10.5    1020.0     629.108349  ...  266.904108         0.09713     1.0

[5 rows x 43 columns]

In [ ]:
numeric_cols = ['meter_waiting','meter_waiting_fare','meter_waiting_till_pickup',
               'additional_fare','duration','pick_lat','pick_lon','drop_lat','drop_lon',
               'fare','pickup_time_day','pickup_time_hour','pickup_time_minute']

numeric_cols = ['meter_waiting','total_additional_fare','meter_waiting_till_pickup',
                'driving_duration','fare','distance',
                'distance_X','distance_Y','direction',
                'pickup_time_hour']
categorical_cols = ['day_of_week']



In [ ]:
imputed_train_set = imputed_set

imputed_train_labels = imputed_set.labels
imputed_train_set = imputed_set.drop('labels', 1)

In [ ]:
X_train, X_eval, Y_train, Y_eval = train_test_split(
    imputed_train_set,
    imputed_train_labels,
    test_size=0.20,
    shuffle=True,
    stratify=imputed_train_labels,
    random_state=RANDOM_SEED
)



In [ ]:
numeric_preprocessing_steps = Pipeline([
    ('minmax_scaler', MinMaxScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OrdinalEncoder())
    ])


preprocessor = ColumnTransformer(
    transformers = [
        ("numeric", numeric_preprocessing_steps, numeric_cols),
        ("categorical", categorical_transformer, categorical_cols)
    ],
    remainder = "drop"
)

data_pipeline = Pipeline([
    ("preprocessor", preprocessor)
])


In [ ]:
data_pipeline.fit(X_train)
d_train = data_pipeline.transform(X_train)
d_eval = data_pipeline.transform(X_eval)

In [ ]:
print(d_train.shape, d_eval.shape)
Y_train.shape

(13740, 11) (3435, 11)


(13740,)

In [ ]:
d_train[0]

array([2.73338477e-04, 4.00624189e-04, 1.07432538e-02, 5.15427478e-02,
       1.31043617e-02, 7.47371196e-02, 5.30865740e-01, 6.62544696e-01,
       8.55723234e-01, 5.21739130e-01, 3.00000000e+00])

In [ ]:
from sklearn.utils.class_weight import compute_sample_weight
sample_w = compute_sample_weight(class_weight={0:5, 1:0.5}, y=Y_train)
#sample_w = compute_sample_weight(class_weight='balanced', y=Y_train)

In [ ]:
sample_w

array([1., 1., 1., ..., 5., 1., 1.])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

gbclf = GradientBoostingClassifier(random_state=2, n_estimators = 5000, max_depth =5, 
                                   subsample = 1.0, verbose = 1)
gbclf.fit(d_train, Y_train, sample_w)
print(gbclf.score(d_eval, Y_eval))
pr = gbclf.predict(d_eval)
print(f1_score(Y_eval, pr, average='macro'))
confusion_matrix(Y_eval, pr)

      Iter       Train Loss   Remaining Time 
         1           1.2933            5.81m
         2           1.2171            5.79m
         3           1.1530            5.79m
         4           1.0998            5.81m
         5           1.0539            5.84m
         6           1.0122            5.82m
         7           0.9765            5.86m
         8           0.9434            5.82m
         9           0.9159            5.81m
        10           0.8915            5.79m
        20           0.7384            5.73m
        30           0.6391            5.69m
        40           0.5815            5.68m
        50           0.5365            5.67m
        60           0.5005            5.65m
        70           0.4696            5.64m
        80           0.4460            5.63m
        90           0.4242            5.62m
       100           0.3987            5.60m
       200           0.2490            5.46m
       300           0.1704            5.34m
       40

array([[ 219,  117],
       [  34, 3065]])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

gbclf = GradientBoostingClassifier(random_state=2, n_estimators = 5000, max_depth =5, 
                                   subsample = 1.0, verbose = 1)
gbclf.fit(d_train, Y_train, sample_w)
print(gbclf.score(d_eval, Y_eval))
pr = gbclf.predict(d_eval)
print(f1_score(Y_eval, pr, average='macro'))
confusion_matrix(Y_eval, pr)

      Iter       Train Loss   Remaining Time 
         1           1.2933            6.52m
         2           1.2171            6.07m
         3           1.1530            6.01m
         4           1.0998            6.06m
         5           1.0539            5.98m
         6           1.0122            5.93m
         7           0.9765            5.88m
         8           0.9434            5.85m
         9           0.9159            5.84m
        10           0.8915            5.82m
        20           0.7384            5.78m
        30           0.6391            5.73m
        40           0.5815            5.70m
        50           0.5365            5.68m
        60           0.5005            5.66m
        70           0.4696            5.65m
        80           0.4460            5.64m
        90           0.4242            5.63m
       100           0.3987            5.62m
       200           0.2490            5.48m
       300           0.1704            5.38m
       40

array([[ 219,  117],
       [  34, 3065]])

In [ ]:
0.9513828238719069
0.8373952513273669

array([[ 196,  140],
       [  27, 3072]])

In [ ]:

confusion_matrix(Y_eval, pr)

array([[ 191,  145],
       [  21, 3078]])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gbclf = GradientBoostingClassifier(random_state=0, n_estimators = 850, max_depth =8, subsample = 1.0, loss ='exponential')
#gbclf.fit(d_train, Y_train, sample_w)
gbclf.fit(d_train, Y_train,sample_w)
gbclf.score(d_eval, Y_eval)

0.9560989982321745

In [ ]:
data_pipeline.fit(imputed_train_set)
d_all = data_pipeline.transform(imputed_train_set)
y_all = imputed_train_labels

sample_w = compute_sample_weight(class_weight={0:5, 1:0.5}, y=y_all)

gbclf = GradientBoostingClassifier(random_state=2, n_estimators = 5000, max_depth =5, 
                                   subsample = 1.0, verbose = 1)

print(d_all.shape, y_all.shape)

gbclf.fit(d_all, y_all,sample_w)

(17175, 11) (17175,)
      Iter       Train Loss   Remaining Time 
         1           1.2957            8.36m
         2           1.2198            7.94m
         3           1.1577            7.71m
         4           1.1041            7.56m
         5           1.0555            7.48m
         6           1.0152            7.48m
         7           0.9793            7.42m
         8           0.9480            7.44m
         9           0.9219            7.42m
        10           0.8977            7.39m
        20           0.7565            7.24m
        30           0.6618            7.17m
        40           0.6143            7.14m
        50           0.5634            7.12m
        60           0.5220            7.11m
        70           0.4938            7.09m
        80           0.4646            7.07m
        90           0.4428            7.05m
       100           0.4216            7.03m
       200           0.2805            6.90m
       300           0.2003      

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=5,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=5000,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=2, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=1,
                           warm_start=False)

In [ ]:
cleaned_test_data = preprocess_train_data(test)

test_set = data_pipeline.transform(cleaned_test_data)

In [ ]:
test_set.shape

(8576, 11)

In [ ]:
preds = gbclf.predict(test_set)
print(preds)

[1. 0. 1. ... 1. 1. 1.]


In [ ]:
preds.shape

(8576,)

In [ ]:
output = pd.DataFrame(test,columns=['tripid'])
output['prediction'] = preds
output = output.astype({"prediction": int})
output.head()

tripid  prediction
0  213284604           1
1  213286352           0
2  213293973           1
3  213294622           1
4  213298687           1

In [ ]:
output.to_csv('/content/Ridefare_submission_32.csv',index=False)