<a href="https://colab.research.google.com/github/chanukaDissanayaka/RideFareClassification/blob/master/Ridefare_submission_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#imports

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from datetime import datetime, timedelta
from pandas import DataFrame

from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier

import numpy as np

RANDOM_SEED = 4

In [0]:
dataframe = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

dataframe.isna().sum(axis = 0)
#dataframe = dataframe.fillna(method='ffill')
dataframe = dataframe.dropna()

In [0]:
def preprocess_train_data(dataframe):
  feature_set = dataframe.iloc[:,1:13]

  features = feature_set

  features['pickup_time'] = pd.to_datetime(features['pickup_time'], format="%m/%d/%Y %H:%M")
  features['drop_time'] = pd.to_datetime(features['drop_time'], format="%m/%d/%Y %H:%M")

  td = features

  td['pickup_time_year'] = td['pickup_time'].dt.year
  td['pickup_time_month'] = td['pickup_time'].dt.month
  td['pickup_time_day'] = td['pickup_time'].dt.day
  td['pickup_time_hour'] = td['pickup_time'].dt.hour
  td['pickup_time_minute'] = td['pickup_time'].dt.minute

  td['drop_time_year'] = td['drop_time'].dt.year
  td['drop_time_month'] = td['drop_time'].dt.month
  td['drop_time_day'] = td['drop_time'].dt.day
  td['drop_time_hour'] = td['drop_time'].dt.hour
  td['drop_time_minute'] = td['drop_time'].dt.minute

  td['day_of_week'] = td['pickup_time'].dt.day_name()
  td['day_of_week'] = OrdinalEncoder().fit_transform(td[['day_of_week']])

  td['duration_calculated'] = td['drop_time'] - td['pickup_time']
  td['duration_calculated'] = td['duration_calculated'].dt.total_seconds().astype(int)

  td = td.drop('pickup_time',1)
  td = td.drop('drop_time',1)

  td = get_trip_distance_eucld(td)
  td = get_X_distance(td)
  td = get_Y_distance(td)
  td = get_pick_XY(td)
  td = get_drop_XY(td)
  td = transform_hour(td)
  td = set_fare_duration(td)
  

  return td

def get_labels(dataframe):
  label_set = dataframe.iloc[:, 13:14]
  #rev_label_set = label_set
  rev_label_set = label_set.replace({'correct':'incorrect', 'incorrect':'correct'})

  encoder = LabelEncoder()
  encoder.fit(rev_label_set)
  labels = encoder.transform(rev_label_set)
  return labels

def set_time_of_the_day(cleaned_train_set):
  cleaned_train_set.head()
  newFrame = cleaned_train_set
  tt = newFrame

  d0_index = newFrame[(newFrame['pickup_time_hour']>=0) & (newFrame['pickup_time_hour'] < 6 )].index
  tt.loc[d0_index,'time_of_day']=0

  d1_index = newFrame[(newFrame['pickup_time_hour']>=6) & (newFrame['pickup_time_hour'] < 12 )].index
  tt.loc[d1_index,'time_of_day']=1

  d2_index = newFrame[(newFrame['pickup_time_hour']>=12) & (newFrame['pickup_time_hour'] < 18 )].index
  tt.loc[d2_index,'time_of_day']=2

  d3_index = newFrame[(newFrame['pickup_time_hour']>=18) & (newFrame['pickup_time_hour'] < 24 )].index
  tt.loc[d3_index,'time_of_day']=3

  return tt

def haversine_distance(lat1, lon1, lat2, lon2):
  r = 6371
  phi1 = np.radians(lat1)
  phi2 = np.radians(lat2)
  d_phi = np.radians(lat2-lat1)
  d_lambda = np.radians(lon2-lon1)

  a = np.sin(d_phi /2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(d_lambda/2)**2
  res = r*(2* np.arctan2(np.sqrt(a), np.sqrt(1-a)))

  return np.round(res,2)
  return res

def get_trip_distance(frame):
  newFrame = frame
  newFrame["distance"] = haversine_distance(frame['pick_lat'],frame['drop_lat'],frame['pick_lon'],frame['drop_lon'])
  return newFrame

def get_trip_distance_eucld(frame):
  newFrame = frame
  newFrame["distance"] = (((frame['pick_lat']-frame['drop_lat'])**2)+((frame['pick_lon']-frame['drop_lon'])**2)**0.5)
  return newFrame

def get_X_distance(frame):
  newFrame = frame
  newFrame["distance_X"] = ((frame['pick_lat']-frame['drop_lat']))
  return newFrame

def get_Y_distance(frame):
  newFrame = frame
  newFrame["distance_Y"] = ((frame['pick_lon']-frame['drop_lon']))
  return newFrame

def get_pick_XY(frame):
  newFrame = frame
  newFrame["pick_X"] = np.cos(frame['pick_lat'])* np.cos(frame['pick_lon'])
  newFrame["pick_Y"] = np.cos(frame['pick_lat'])* np.sin(frame['pick_lon'])
  return newFrame

def get_drop_XY(frame):
  newFrame = frame
  newFrame["drop_X"] = np.cos(frame['drop_lat'])* np.cos(frame['drop_lon'])
  newFrame["drop_Y"] = np.cos(frame['drop_lat'])* np.sin(frame['drop_lon'])
  return newFrame

def transform_hour(frame):
  newFrame = frame
  newFrame["pick_hour_sin"] = np.sin(np.radians(3*frame['pickup_time_hour']))
  newFrame["drop_hour_sin"] = np.sin(np.radians(3*frame['drop_time_hour']))

  newFrame["pick_hour_cos"] = np.cos(np.radians(3*frame['pickup_time_hour']))
  newFrame["drop_hour_cos"] = np.cos(np.radians(3*frame['drop_time_hour']))
  return newFrame

def set_fare_duration(imputed_train_set):
  df = imputed_train_set

  df['total_fare'] = ((df['fare']-df['fare'].mean())/df['fare'].std() +
                      (df['additional_fare']-df['additional_fare'].mean())/df['additional_fare'].std()+ 
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std())

  df['total_fare'] =  df['fare'] + df['additional_fare'] + df['meter_waiting_fare']
  df['total_additional_fare'] = df['additional_fare'] + df['meter_waiting_fare']
  df['total_waiting_time'] = df['meter_waiting'] + df['meter_waiting_till_pickup']
  df['total_time'] = df['total_waiting_time'] + df['duration']

  df['waiting_factor'] = ((df['meter_waiting']-df['meter_waiting'].mean())/df['meter_waiting'].std() +
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std()+ 
                      (df['meter_waiting_till_pickup']-df['meter_waiting_till_pickup'].mean())/df['meter_waiting_till_pickup'].std())

  return df

In [0]:
print(dataframe.label.value_counts())

correct      15442
incorrect     1526
Name: label, dtype: int64


In [0]:
cleaned_train_set = preprocess_train_data(dataframe)
labels = get_labels(dataframe)
cleaned_train_set.head()


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


additional_fare  duration  ...  total_time  waiting_factor
0             10.5     834.0  ...       954.0       -0.249539
1             10.5     791.0  ...       972.0       -0.092330
2             10.5    1087.0  ...      1228.0       -0.253348
3             10.5     598.0  ...       937.0       -0.180187
5             10.5    3407.0  ...      3701.0       -0.125349

[5 rows x 38 columns]

In [0]:
from sklearn.impute import SimpleImputer

cleaned_train_set.duration.fillna(cleaned_train_set.duration_calculated, inplace=True)
cleaned_train_set.head()

imp_mean = SimpleImputer(missing_values=np.nan, strategy='median')
dframe = imp_mean.fit_transform(cleaned_train_set)
k = cleaned_train_set.keys()
imputed_train_set = cleaned_train_set
imputed_train_set[k] = dframe
imputed_train_set.head()

additional_fare  duration  ...  total_time  waiting_factor
0             10.5     834.0  ...       954.0       -0.249539
1             10.5     791.0  ...       972.0       -0.092330
2             10.5    1087.0  ...      1228.0       -0.253348
3             10.5     598.0  ...       937.0       -0.180187
5             10.5    3407.0  ...      3701.0       -0.125349

[5 rows x 38 columns]

In [0]:
def set_fare_duration(imputed_train_set):
  df = imputed_train_set

  df['total_fare'] = ((df['fare']-df['fare'].mean())/df['fare'].std() +
                      (df['additional_fare']-df['additional_fare'].mean())/df['additional_fare'].std()+ 
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std())

  df['total_fare'] =  df['fare'] + df['additional_fare'] + df['meter_waiting_fare']
  df['total_additional_fare'] = df['additional_fare'] + df['meter_waiting_fare']
  df['total_waiting_time'] = df['meter_waiting'] + df['meter_waiting_till_pickup']
  df['total_time'] = df['total_waiting_time'] + df['duration']

  df['waiting_factor'] = ((df['meter_waiting']-df['meter_waiting'].mean())/df['meter_waiting'].std() +
                      (df['meter_waiting_fare']-df['meter_waiting_fare'].mean())/df['meter_waiting_fare'].std()+ 
                      (df['meter_waiting_till_pickup']-df['meter_waiting_till_pickup'].mean())/df['meter_waiting_till_pickup'].std())

  return df

In [0]:
from sklearn.cluster import KMeans

tt = imputed_train_set
tt['duration_type'] = 0
tt['fare_type'] = 0

d0_index = tt[(tt['duration'] <= 500) ].index
tt.loc[d0_index,'duration_type']=0

d1_index = tt[(tt['duration'] > 500) & (tt['duration'] <= 1000) ].index
tt.loc[d1_index,'duration_type']=1

d2_index = tt[(tt['duration'] > 1000)].index
tt.loc[d2_index,'duration_type']=2

d0_index = tt[(tt['fare'] <= 100) ].index
tt.loc[d0_index,'fare_type']=0

d1_index = tt[(tt['fare'] > 100) & (tt['fare'] <= 800) ].index
tt.loc[d1_index,'fare_type']=1

d2_index = tt[(tt['fare'] > 1000)].index
tt.loc[d2_index,'fare_type']=2

imputed_train_set = tt

In [0]:
imputed_train_set.head()

additional_fare  duration  ...  total_time  waiting_factor
0             10.5     834.0  ...       954.0       -0.249539
1             10.5     791.0  ...       972.0       -0.092330
2             10.5    1087.0  ...      1228.0       -0.253348
3             10.5     598.0  ...       937.0       -0.180187
5             10.5    3407.0  ...      3701.0       -0.125349

[5 rows x 38 columns]

In [0]:
numeric_cols = ['meter_waiting','meter_waiting_fare','meter_waiting_till_pickup',
               'additional_fare','duration','pick_lat','pick_lon','drop_lat','drop_lon',
               'fare','pickup_time_day','pickup_time_hour','pickup_time_minute']

numeric_cols = ['meter_waiting','meter_waiting_fare','meter_waiting_till_pickup',
               'additional_fare','duration','fare','distance','waiting_factor',
                'distance_X', 'distance_Y']
categorical_cols = []



In [0]:
X_train, X_eval, Y_train, Y_eval = train_test_split(
    imputed_train_set,
    labels,
    test_size=0.20,
    shuffle=True,
    stratify=labels,
    random_state=RANDOM_SEED
)



In [0]:
numeric_preprocessing_steps = Pipeline([
    ('minmax_scaler', MinMaxScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OrdinalEncoder())
    ])


preprocessor = ColumnTransformer(
    transformers = [
        ("numeric", numeric_preprocessing_steps, numeric_cols),
        ("categorical", categorical_transformer, categorical_cols)
    ],
    remainder = "drop"
)

data_pipeline = Pipeline([
    ("preprocessor", preprocessor)
])


In [0]:
data_pipeline.fit(X_train)
d_train = data_pipeline.transform(X_train)
d_eval = data_pipeline.transform(X_eval)

In [0]:
print(d_train.shape, d_eval.shape)
Y_train.shape

(13574, 8) (3394, 8)


(13574,)

In [0]:
d_train[0]

array([2.13821228e-04, 0.00000000e+00, 2.06676026e-03, 8.20631136e-04,
       1.33297494e-03, 5.27573862e-03, 5.29539131e-07, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00])

In [0]:
from sklearn.utils.class_weight import compute_sample_weight
sample_w = compute_sample_weight(class_weight={0:0.1, 1:0.90}, y=Y_train)

In [0]:
from sklearn.utils.class_weight import compute_sample_weight
sample_w = compute_sample_weight(class_weight={0:5, 1:1}, y=Y_train)

In [0]:
sample_w

array([1., 1., 1., ..., 1., 1., 1.])

In [0]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

gbclf = GradientBoostingClassifier(random_state=2, n_estimators = 1000, max_depth =8, 
                                   subsample = 1.0, verbose = 1)
gbclf.fit(d_train, Y_train, sample_w)
print(gbclf.score(d_eval, Y_eval))
pr = gbclf.predict(d_eval)
f1_score(Y_eval, pr, average='macro')

      Iter       Train Loss   Remaining Time 
         1           1.1665            1.65m
         2           1.0869            1.64m
         3           1.0202            1.64m
         4           0.9646            1.64m
         5           0.9140            1.67m
         6           0.8706            1.69m
         7           0.8279            1.70m
         8           0.7896            1.69m
         9           0.7561            1.68m
        10           0.7268            1.68m
        20           0.5411            1.64m
        30           0.4156            1.61m
        40           0.3254            1.59m
        50           0.2706            1.57m
        60           0.2312            1.55m
        70           0.1970            1.53m
        80           0.1734            1.52m
        90           0.1536            1.50m
       100           0.1375            1.48m
       200           0.0508            1.31m
       300           0.0212            1.15m
       40

0.8341393608516814

In [0]:
from sklearn.ensemble import GradientBoostingClassifier

gbclf = GradientBoostingClassifier(random_state=0, n_estimators = 850, max_depth =8, subsample = 1.0, loss ='exponential')
#gbclf.fit(d_train, Y_train, sample_w)
gbclf.fit(d_train, Y_train,sample_w)
gbclf.score(d_eval, Y_eval)

0.9560989982321745

In [0]:
from sklearn.neural_network import MLPClassifier

mlpclf = MLPClassifier(random_state=1, max_iter=4000, verbose = True, alpha = 0.1,
                    hidden_layer_sizes = (64,32,8),solver = "lbfgs", early_stopping=True)
mlpclf.fit(d_train, Y_train)
mlpclf.score(d_eval, Y_eval)

0.9124926340601061

In [0]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=40, random_state=0, class_weight = {0:5, 1:1},
                             oob_score = True)
clf.fit(d_train, Y_train)
clf.score(d_eval, Y_eval)


0.9438300349243306

In [0]:
from xgboost import XGBClassifier

xgb = XGBClassifier(max_depth=60,reg_alpha=0.0001, reg_lambda=0.01,
       scale_pos_weight=8, seed=0, silent=False, subsample=1,
       min_child_weight=1,n_estimators=2000,)

xgb.fit(d_train, Y_train)
pr = xgb.predict(d_eval)
f1_score(Y_eval, pr, average='micro')

0.9476135040745053

In [0]:
f1_score(Y_eval, pr, average='macro')

0.8293281605893529

0.9458672875436555

In [0]:
data_pipeline.fit(imputed_train_set)
d_all = data_pipeline.transform(imputed_train_set)
y_all = labels
print(d_all.shape, y_all.shape)

(17176, 10) (17176,)


In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores = cross_val_score(gbclf, d_all, y_all, scoring='roc_auc', cv=cv, n_jobs=-1)
print('Mean ROC AUC: %.5f' % mean(scores))

In [0]:
from keras import metrics
import tensorflow as tf

def recall(y_true, y_pred):
    y_true = K.ones_like(y_true) 
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    all_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    
    recall = true_positives / (all_positives + K.epsilon())
    return recall

def precision(y_true, y_pred):
    y_true = K.ones_like(y_true) 
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision

def f1_score(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [0]:
model = Sequential()
model.add(Dense(80, input_dim=5, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=[tf.keras.metrics.Precision(), 
                        tf.keras.metrics.Recall()])

In [0]:
model.fit(d_train, Y_train,batch_size=20, epochs=100)
pm = model.predict_classes(d_eval)

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

print(f1_score(Y_eval, pm, average='micro'))
confusion_matrix(Y_eval,pm)

Epoch 1/100
13740/13740 [==============================] - 1s 72us/step - loss: 0.3414 - precision_4: 0.9004 - recall_4: 0.9941
Epoch 2/100
13740/13740 [==============================] - 1s 63us/step - loss: 0.3080 - precision_4: 0.9024 - recall_4: 0.9994
Epoch 3/100
13740/13740 [==============================] - 1s 63us/step - loss: 0.3053 - precision_4: 0.9024 - recall_4: 0.9997
Epoch 4/100
13740/13740 [==============================] - 1s 64us/step - loss: 0.3048 - precision_4: 0.9023 - recall_4: 0.9998
Epoch 5/100
13740/13740 [==============================] - 1s 62us/step - loss: 0.3031 - precision_4: 0.9022 - recall_4: 0.9998
Epoch 6/100
13740/13740 [==============================] - 1s 63us/step - loss: 0.3030 - precision_4: 0.9021 - recall_4: 0.9999
Epoch 7/100
13740/13740 [==============================] - 1s 62us/step - loss: 0.3026 - precision_4: 0.9022 - recall_4: 0.9999
Epoch 8/100
13740/13740 [==============================] - 1s 64us/step - loss: 0.3014 - precision_4: 0.

array([[ 179,  157],
       [  55, 3045]])

In [0]:
cleaned_test_data = preprocess_train_data(test)

test_set = data_pipeline.transform(cleaned_test_data)

In [0]:
test_set.shape

(8576, 11)

In [0]:
preds = gbclf.predict(test_set)
print(preds)

[1 1 1 ... 1 1 1]


In [0]:
preds.shape

(8576,)

In [0]:
output = pd.DataFrame(test,columns=['tripid'])
output['prediction'] = preds
output.head()

tripid  prediction
0  213284604           1
1  213286352           1
2  213293973           1
3  213294622           1
4  213298687           1

In [0]:
output.to_csv('/content/Ridefare_submission_14.csv',index=False)

In [0]:
base = gbclf.predict(d_eval)
#print("keras", f1_score(Y_eval, eval_predict, average='micro'))
print("base", f1_score(Y_eval, base, average='micro'))

from sklearn.metrics import confusion_matrix

results = gbclf.predict(d_eval)
confusion_matrix(Y_eval, results)

base 0.9490276959340012


array([[ 170,  135],
       [  38, 3051]])

In [0]:
k =0
for i in pred_proba:
  print("%0.5f"%i[0],"%0.4f"%i[1], Y_eval[k])
  k = k+1

In [0]:
pred_proba = gbclf.predict_proba(d_eval)

threshold = 0.3

preds = (pred_proba [:,1] >= threshold).astype('int')

In [0]:
base = gbclf.predict(d_eval)
#print("keras", f1_score(Y_eval, eval_predict, average='micro'))
print("base", f1_score(Y_eval, base, average='micro'))

from sklearn.metrics import confusion_matrix

results = gbclf.predict(d_eval)
confusion_matrix(Y_eval, results)

In [0]:
pred_proba = gbclf.predict_proba(d_eval)

threshold = 0.05

preds = (pred_proba [:,0] <= threshold).astype('int')

In [0]:
print(preds)
print("base", f1_score(Y_eval, preds, average='micro'))
confusion_matrix(Y_eval, preds)

[1 0 1 ... 1 1 1]
base 0.940777843252799


array([[ 200,  105],
       [  96, 2993]])

In [0]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, class_weight={0:1, 1:8}, max_depth = 20)
clf.fit(d_train, Y_train)
clf.score(d_eval, Y_eval)

0.9281084266352386

In [0]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

test = SelectKBest(score_func=f_classif, k=17)
fit = test.fit(X_train, Y_train)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features_selected = fit.transform(cleaned_train_set)

k = cleaned_train_set.keys()
j =0
for i in fit.scores_:
  print (i, k[j])
  j = j+1

[2.560e+01 1.501e+02 1.365e+02 1.262e+02 1.618e+01 4.756e+00 1.069e+01
 4.670e-01 6.644e+00 4.090e+02 3.445e-01 1.521e-01 4.540e-01 2.967e-01
 3.661e-01 9.497e-05 1.896e-01]
25.601700516148178 additional_fare
150.1423482323858 duration
136.53814018608236 meter_waiting
126.15291654442362 meter_waiting_fare
16.176969168253855 meter_waiting_till_pickup
4.755913729479669 pick_lat
10.68640597221555 pick_lon
0.46699771908048066 drop_lat
6.644427453624097 drop_lon
409.0290439880105 fare
0.3444733818253683 pickup_time_day
0.15214708901589488 pickup_time_hour
0.45403506787917486 pickup_time_minute
0.2967370493315319 drop_time_day
0.3660508242748645 drop_time_hour
9.497351291964044e-05 drop_time_minute
0.18958475782896403 time_of_day
